import "@/app/global.css";
import fs from "fs";
import path from "path";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import StorageInitializer from "@/components/StorageInitializer";
import { ArrowLeft } from "lucide-react";
import HeaderElement from "@/components/HeaderElement";
import ButtonElement from "@/components/ButtonElement";

function getFallbackData() {
  try {
    const filePath = path.join(process.cwd(), "data", "fallback.json");
    const jsonData = fs.readFileSync(filePath, "utf-8");

    return JSON.parse(jsonData);
  } catch (error) {
    console.error("Gagal membaca file fallback.json:", error);
    return { users: [], categories: [], topics: [], custom_ai_topics: [], learning_histories: [] };
  }
}

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const fallbackData = getFallbackData();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full w-screen flex flex-col bg-neutral-50">
        <StorageInitializer initialData={fallbackData} />

        { children }

      </body>
    </html>
  );
}
